name: GitVersion Tag

permissions:
  id-token: write
  contents: write

on:
  push:
    branches: [ "main" ]

#  pull_request:
#    branches: [ "main" ]

  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Tag the repo
      uses: ./.github/actions/gvtag
        