name: GitVersion Tag

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

#  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.8
        with:
          inlineScript: |
            az account show
          # azcliversion: # optional, default is agentazcliversion
