name: Publish Module

permissions:
  id-token: write
  contents: read

on:
  push:
    tags:
    - '*'

#  pull_request:
#    branches: [ "main" ]

  workflow_dispatch:
jobs:
  publish:
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.8
        with:
          inlineScript: |
            az bicep publish --force --file ./module/network.bicep --target br:eruza.azurecr.io/bicep/modules/network:v${{ github.refName }}
          # azcliversion: # optional, default is agentazcliversion
